In [4]:
#importing libraries 

import pandas as pd
import json

**Process Match result**

In [5]:
#opning match result file
with open('D:/harshita/project/file2/t20_json_files/match_results.json') as f:
    data = json.load(f)

#data[0]['matchSummary'] 

#convert it into datafram
df_match = pd.DataFrame(data[0]['matchSummary'])
df_match

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
5,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
6,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
7,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
8,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
9,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
10,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
11,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
12,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
13,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
14,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
15,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
16,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
17,South Africa,Zimbabwe,no result,,Hobart,"Oct 24, 2022",T20I # 1844
18,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
19,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
20,Afghanistan,New Zealand,abandoned,,Melbourne,"Oct 26, 2022",T20I # 1846a
21,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
22,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
23,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
24,Afghanistan,Ireland,abandoned,,Melbourne,"Oct 28, 2022",T20I # 1849a
25,Australia,England,abandoned,,Melbourne,"Oct 28, 2022",T20I # 1849b
26,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
27,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
28,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
29,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
30,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
31,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
32,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
33,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
34,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
35,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
36,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
37,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
38,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
39,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
40,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
41,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
42,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
43,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
44,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879

**Renaming scorecard column as match id to link with other tables**

In [6]:
#renaming the column name scorecard to match_id
df_match.rename({'scorecard':'match_id'},axis= 1,inplace=True)

**create a match dictionary that maps team names to unique match id. this will be helpfull later to link with other table**

In [14]:

match_dict={}
for index, row in df_match.iterrows():
    key1 = row['team1'] + ' Vs ' + row['team2']
    key2 = row['team2'] + ' Vs ' + row['team1']
    match_dict[key1]= row['match_id']
    match_dict[key2]= row['match_id']
match_dict

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia': 'T20I # 1823',
 'Netherlands Vs U.A.E.': 'T20I # 1825',
 'U.A.E. Vs Netherlands': 'T20I # 1825',
 'Scotland Vs West Indies': 'T20I # 1826',
 'West Indies Vs Scotland': 'T20I # 1826',
 'Ireland Vs Zimbabwe': 'T20I # 1828',
 'Zimbabwe Vs Ireland': 'T20I # 1828',
 'Namibia Vs Netherlands': 'T20I # 1830',
 'Netherlands Vs Namibia': 'T20I # 1830',
 'Sri Lanka Vs U.A.E.': 'T20I # 1832',
 'U.A.E. Vs Sri Lanka': 'T20I # 1832',
 'Ireland Vs Scotland': 'T20I # 1833',
 'Scotland Vs Ireland': 'T20I # 1833',
 'West Indies Vs Zimbabwe': 'T20I # 1834',
 'Zimbabwe Vs West Indies': 'T20I # 1834',
 'Netherlands Vs Sri Lanka': 'T20I # 1835',
 'Sri Lanka Vs Netherlands': 'T20I # 1835',
 'Namibia Vs U.A.E.': 'T20I # 1836',
 'U.A.E. Vs Namibia': 'T20I # 1836',
 'Ireland Vs West Indies': 'T20I # 1837',
 'West Indies Vs Ireland': 'T20I # 1837',
 'Scotland Vs Zimbabwe': 'T20I # 1838',
 'Zimbabwe Vs Scotland': 'T20I # 1838',
 'Australia Vs New Zealand': 'T20I # 1839',
 'New Zealand Vs Australia': 'T20I # 1839',
 'Afghanistan Vs England': 'T20I # 1840',
 'England Vs Afghanistan': 'T20I # 1840',
 'Ireland Vs Sri Lanka': 'T20I # 1841',
 'Sri Lanka Vs Ireland': 'T20I # 1841',
 'India Vs Pakistan': 'T20I # 1842',
 'Pakistan Vs India': 'T20I # 1842',
 'Bangladesh Vs Netherlands': 'T20I # 1843',
 'Netherlands Vs Bangladesh': 'T20I # 1843',
 'South Africa Vs Zimbabwe': 'T20I # 1844',
 'Zimbabwe Vs South Africa': 'T20I # 1844',
 'Australia Vs Sri Lanka': 'T20I # 1845',
 'Sri Lanka Vs Australia': 'T20I # 1845',
 'England Vs Ireland': 'T20I # 1846',
 'Ireland Vs England': 'T20I # 1846',
 'Afghanistan Vs New Zealand': 'T20I # 1846a',
 'New Zealand Vs Afghanistan': 'T20I # 1846a',
 'Bangladesh Vs South Africa': 'T20I # 1847',
 'South Africa Vs Bangladesh': 'T20I # 1847',
 'India Vs Netherlands': 'T20I # 1848',
 'Netherlands Vs India': 'T20I # 1848',
 'Pakistan Vs Zimbabwe': 'T20I # 1849',
 'Zimbabwe Vs Pakistan': 'T20I # 1849',
 'Afghanistan Vs Ireland': 'T20I # 1849a',
 'Ireland Vs Afghanistan': 'T20I # 1849a',
 'Australia Vs England': 'T20I # 1849b',
 'England Vs Australia': 'T20I # 1849b',
 'New Zealand Vs Sri Lanka': 'T20I # 1850',
 'Sri Lanka Vs New Zealand': 'T20I # 1850',
 'Bangladesh Vs Zimbabwe': 'T20I # 1851',
 'Zimbabwe Vs Bangladesh': 'T20I # 1851',
 'Netherlands Vs Pakistan': 'T20I # 1852',
 'Pakistan Vs Netherlands': 'T20I # 1852',
 'India Vs South Africa': 'T20I # 1853',
 'South Africa Vs India': 'T20I # 1853',
 'Australia Vs Ireland': 'T20I # 1855',
 'Ireland Vs Australia': 'T20I # 1855',
 'Afghanistan Vs Sri Lanka': 'T20I # 1856',
 'Sri Lanka Vs Afghanistan': 'T20I # 1856',
 'England Vs New Zealand': 'T20I # 1858',
 'New Zealand Vs England': 'T20I # 1858',
 'Netherlands Vs Zimbabwe': 'T20I # 1859',
 'Zimbabwe Vs Netherlands': 'T20I # 1859',
 'Bangladesh Vs India': 'T20I # 1860',
 'India Vs Bangladesh': 'T20I # 1860',
 'Pakistan Vs South Africa': 'T20I # 1861',
 'South Africa Vs Pakistan': 'T20I # 1861',
 'Ireland Vs New Zealand': 'T20I # 1862',
 'New Zealand Vs Ireland': 'T20I # 1862',
 'Australia Vs Afghanistan': 'T20I # 1864',
 'Afghanistan Vs Australia': 'T20I # 1864',
 'England Vs Sri Lanka': 'T20I # 1867',
 'Sri Lanka Vs England': 'T20I # 1867',
 'Netherlands Vs South Africa': 'T20I # 1871',
 'South Africa Vs Netherlands': 'T20I # 1871',
 'Bangladesh Vs Pakistan': 'T20I # 1872',
 'Pakistan Vs Bangladesh': 'T20I # 1872',
 'India Vs Zimbabwe': 'T20I # 1873',
 'Zimbabwe Vs India': 'T20I # 1873',
 'New Zealand Vs Pakistan': 'T20I # 1877',
 'Pakistan Vs New Zealand': 'T20I # 1877',
 'England Vs India': 'T20I # 1878',
 'India Vs England': 'T20I # 1878',
 'England Vs Pakistan': 'T20I # 1879',
 'Pakistan Vs England': 'T20I # 1879'}

In [39]:
df_match.to_csv('D:/harshita/project/file2/csv/match.csv', index = False)

**process batting summary**

In [9]:
#opening file 'batting summary'

with open('D:/harshita/project/file2/t20_json_files/batting_summary.json') as f:
    data = json.load(f)   

#collecting all data together
all_records=[]
for rec in data:
    all_records.extend(rec['battingSummary'])

#creating dataframe
df_batting = pd.DataFrame(all_records)

df_batting.head(5)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33

In [10]:
#adding new column 'out or not-out'
df_batting['out/not_out']= df_batting.dismissal.apply(lambda x: 'out' if len(x)>0 else 'not-out' )
df_batting.head(5)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out

In [15]:
#create a new column called 'match_id'
df_batting['match_id'] = df_batting['match'].map(match_dict)
df_batting.head(5)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out,T20I # 1823

In [19]:
#delete the column named 'dismissal'
df_batting.drop(columns= ["dismissal"],inplace= True)
df_batting.head(10)

KeyError: "['dismissal'] not found in axis"

In [13]:
df_batting.head(50)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not-out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,out
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,out
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,out
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,not-out
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,out
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,out
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,out
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravindâ€,18,21,0,0,85.71,out
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,out
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,out
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),1,2,0,0,50.00,out
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,out
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,not-out
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,not-out
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,out
30,U.A.E. Vs Netherlands,Netherlands,2,Max O'Dowd,23,18,3,1,127.77,out
31,U.A.E. Vs Netherlands,Netherlands,3,Bas de Leede,14,18,1,0,77.77,out
32,U.A.E. Vs Netherlands,Netherlands,4,Colin Ackermann,17,19,1,0,89.47,out
33,U.A.E. Vs Netherlands,Netherlands,5,Tom Cooper,8,16,0,0,50.00,out
34,U.A.E. Vs Netherlands,Netherlands,6,Scott Edwards(c)â€,16,19,0,0,84.21,not-out
35,U.A.E. Vs Netherlands,Netherlands,7,Roelof van der Merwe,0,2,0,0,0.00,out
36,U.A.E. Vs Netherlands,Netherlands,8,Tim Pringle,15,16,0,0,93.75,out
37,U.A.E. Vs Netherlands,Netherlands,9,Logan van Beek,4,4,0,0,100.00,not-out
38,Scotland Vs West Indies,Scotland,1,George Munsey,66,53,9,0,124.52,not-out
39,Scotland Vs West Indies,Scotland,2,Michael Jones,20,17,3,0,117.64,out
40,Scotland Vs West Indies,Scotland,3,Matthew Crossâ€,3,5,0,0,60.00,out
41,Scotland Vs West Indies,Scotland,4,Richie Berrington(c),16,14,0,1,114.28,out
42,Scotland Vs West Indies,Scotland,5,Calum MacLeod,23,14,4,0,164.28,out
43,Scotland Vs West Indies,Scotland,6,Michael Leask,4,6,0,0,66.66,out
44,Scotland Vs West Indies,Scotland,7,Chris Greaves,16,11,2,0,145.45,not-out
45,Scotland Vs West Indies,West Indies,1,Kyle Mayers,20,13,3,1,153.84,out
46,Scotland Vs West Indies,West Indies,2,Evin Lewis,14,13,1,1,107.69,out
47,Scotland Vs West Indies,West Indies,3,Brandon King,17,15,3,0,113.33,out
48,Scotland Vs West Indies,West Indies,4,Nicholas Pooran(c)â€,5,9,0,0,55.55,out
49,Scotland Vs West Indies,West Indies,5,Shamarh Brooks,4,9,0,0,44.44,out

**clean weird characters**

In [15]:
#modifications in batsmanname
df_batting['batsmanName']= df_batting['batsmanName'].apply(lambda x : x.replace('â€',' '))

df_batting.head(50)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not-out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,out
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,out
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,out
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,not-out
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,out
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,out
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,out
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,18,21,0,0,85.71,out
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,out
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,out
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),1,2,0,0,50.00,out
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,out
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,not-out
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,not-out
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,out
30,U.A.E. Vs Netherlands,Netherlands,2,Max O'Dowd,23,18,3,1,127.77,out
31,U.A.E. Vs Netherlands,Netherlands,3,Bas de Leede,14,18,1,0,77.77,out
32,U.A.E. Vs Netherlands,Netherlands,4,Colin Ackermann,17,19,1,0,89.47,out
33,U.A.E. Vs Netherlands,Netherlands,5,Tom Cooper,8,16,0,0,50.00,out
34,U.A.E. Vs Netherlands,Netherlands,6,Scott Edwards(c),16,19,0,0,84.21,not-out
35,U.A.E. Vs Netherlands,Netherlands,7,Roelof van der Merwe,0,2,0,0,0.00,out
36,U.A.E. Vs Netherlands,Netherlands,8,Tim Pringle,15,16,0,0,93.75,out
37,U.A.E. Vs Netherlands,Netherlands,9,Logan van Beek,4,4,0,0,100.00,not-out
38,Scotland Vs West Indies,Scotland,1,George Munsey,66,53,9,0,124.52,not-out
39,Scotland Vs West Indies,Scotland,2,Michael Jones,20,17,3,0,117.64,out
40,Scotland Vs West Indies,Scotland,3,Matthew Cross,3,5,0,0,60.00,out
41,Scotland Vs West Indies,Scotland,4,Richie Berrington(c),16,14,0,1,114.28,out
42,Scotland Vs West Indies,Scotland,5,Calum MacLeod,23,14,4,0,164.28,out
43,Scotland Vs West Indies,Scotland,6,Michael Leask,4,6,0,0,66.66,out
44,Scotland Vs West Indies,Scotland,7,Chris Greaves,16,11,2,0,145.45,not-out
45,Scotland Vs West Indies,West Indies,1,Kyle Mayers,20,13,3,1,153.84,out
46,Scotland Vs West Indies,West Indies,2,Evin Lewis,14,13,1,1,107.69,out
47,Scotland Vs West Indies,West Indies,3,Brandon King,17,15,3,0,113.33,out
48,Scotland Vs West Indies,West Indies,4,Nicholas Pooran(c),5,9,0,0,55.55,out
49,Scotland Vs West Indies,West Indies,5,Shamarh Brooks,4,9,0,0,44.44,out

In [16]:
df_batting['batsmanName']= df_batting['batsmanName'].apply(lambda x : x.replace('(c)',' '))

df_batting.head(50)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not-out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka,29,23,2,1,126.08,out
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,out
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,out
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,out
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,not-out
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,out
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,out
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,out
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,18,21,0,0,85.71,out
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,out
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,out
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan,1,2,0,0,50.00,out
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,out
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,not-out
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,not-out
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,out
30,U.A.E. Vs Netherlands,Netherlands,2,Max O'Dowd,23,18,3,1,127.77,out
31,U.A.E. Vs Netherlands,Netherlands,3,Bas de Leede,14,18,1,0,77.77,out
32,U.A.E. Vs Netherlands,Netherlands,4,Colin Ackermann,17,19,1,0,89.47,out
33,U.A.E. Vs Netherlands,Netherlands,5,Tom Cooper,8,16,0,0,50.00,out
34,U.A.E. Vs Netherlands,Netherlands,6,Scott Edwards,16,19,0,0,84.21,not-out
35,U.A.E. Vs Netherlands,Netherlands,7,Roelof van der Merwe,0,2,0,0,0.00,out
36,U.A.E. Vs Netherlands,Netherlands,8,Tim Pringle,15,16,0,0,93.75,out
37,U.A.E. Vs Netherlands,Netherlands,9,Logan van Beek,4,4,0,0,100.00,not-out
38,Scotland Vs West Indies,Scotland,1,George Munsey,66,53,9,0,124.52,not-out
39,Scotland Vs West Indies,Scotland,2,Michael Jones,20,17,3,0,117.64,out
40,Scotland Vs West Indies,Scotland,3,Matthew Cross,3,5,0,0,60.00,out
41,Scotland Vs West Indies,Scotland,4,Richie Berrington,16,14,0,1,114.28,out
42,Scotland Vs West Indies,Scotland,5,Calum MacLeod,23,14,4,0,164.28,out
43,Scotland Vs West Indies,Scotland,6,Michael Leask,4,6,0,0,66.66,out
44,Scotland Vs West Indies,Scotland,7,Chris Greaves,16,11,2,0,145.45,not-out
45,Scotland Vs West Indies,West Indies,1,Kyle Mayers,20,13,3,1,153.84,out
46,Scotland Vs West Indies,West Indies,2,Evin Lewis,14,13,1,1,107.69,out
47,Scotland Vs West Indies,West Indies,3,Brandon King,17,15,3,0,113.33,out
48,Scotland Vs West Indies,West Indies,4,Nicholas Pooran,5,9,0,0,55.55,out
49,Scotland Vs West Indies,West Indies,5,Shamarh Brooks,4,9,0,0,44.44,out

In [20]:
df_batting.to_csv('D:/harshita/project/file2/csv/batting_summary.csv',index=False)

**process bowling summary**

In [25]:
with open('D:/harshita/project/file2/t20_json_files/bowling_summary.json') as f:
    data = json.load(f)
    all_record=[]
    for rec in data:
        all_record.extend(rec['bowlingSummary'])
all_record[:2]

[{'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Maheesh Theekshana',
  'overs': '4',
  'maiden': '0',
  'runs': '23',
  'wickets': '1',
  'economy': '5.75',
  '0s': '7',
  '4s': '0',
  '6s': '0',
  'wides': '2',
  'noBalls': '0'},
 {'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Dushmantha Chameera',
  'overs': '4',
  'maiden': '0',
  'runs': '39',
  'wickets': '1',
  'economy': '9.75',
  '0s': '6',
  '4s': '3',
  '6s': '1',
  'wides': '2',
  'noBalls': '0'}]

In [27]:
df_bowling= pd.DataFrame(all_record)
df_bowling.head(5)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0

In [28]:
df_bowling['match_id']= df_bowling['match'].map(match_dict)
df_bowling.head(4)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823

In [30]:
df_bowling.to_csv('D:/harshita/project/file2/csv/bowling_summary.csv',index=False)

**process player information**

In [32]:
with open("D:/harshita/project/file2/t20_json_files/player_info.json") as f:
    data = json.load(f)

In [34]:
df_player= pd.DataFrame(data)
df_player.head(5)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,

**delete extra character**

In [35]:
df_player['name']= df_player['name'].apply(lambda x: x.replace('â€', ''))
df_player['name']= df_player['name'].apply(lambda x: x.replace('(c)', ''))
df_player['name']= df_player['name'].apply(lambda x: x.replace('\xa0', ''))
df_player['name']= df_player['name'].apply(lambda x: x.replace('†', ''))
df_player.head(30)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendis,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunathilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka,Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."
15,Chamika Karunaratne,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowling Allrounder,
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,
19,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
20,Bernard Scholtz,Namibia,Right hand Bat,Slow Left arm Orthodox,Bowler,Bernard Scholtz's brother Nicolaas is currentl...
21,Ben Shikongo,Namibia,Right hand Bat,Right arm Medium fast,Bowler,
22,Charith Asalanka,Sri Lanka,Left hand Bat,Right arm Offbreak,Batting Allrounder,
23,David Warner,Australia,Left hand Bat,Legbreak,Opening Batter,David Warner's extraordinary batting feats in ...
24,Aaron Finch,Australia,Right hand Bat,Slow Left arm Orthodox,Top order Batter,"A solidly built, aggressive batter from a coun..."
25,Mitchell Marsh,Australia,Right hand Bat,Right arm Medium,Allrounder,Part of one of the most well-known family name...
26,Glenn Maxwell,Australia,Right hand Bat,Right arm Offbreak,Batting Allrounder,"One of the fastest scorers in world cricket, G..."
27,Marcus Stoinis,Australia,Right hand Bat,Right arm Medium,Batting Allrounder,"A powerful, versatile batter and medium-pace b..."
28,Josh Hazlewood,Australia,Left hand Bat,Right arm Fast medium,Bowler,A tall and accurate fast bowler who is unrelen...
29,Pat Cummins,Australia,Right hand Bat,Right arm Fast,Bowler,Earmarked as a potential star from a young age...

In [36]:
df_player[df_player['team']== 'India']

,name,team,battingStyle,bowlingStyle,playingRole,description
127,KL Rahul,India,Right hand Bat,,Opening Batter,"A tall, elegant right-hand batsman who can kee..."
128,Rohit Sharma,India,Right hand Bat,Right arm Offbreak,Top order Batter,"Languid and easy on the eye, Rohit Sharma owne..."
129,Virat Kohli,India,Right hand Bat,Right arm Medium,Top order Batter,India has given to the world many a great cric...
130,Suryakumar Yadav,India,Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter,Hard-hitting 360-degree batter Suryakumar Yada...
131,Axar Patel,India,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,Left-arm spinner Axar Patel has been increasin...
132,Hardik Pandya,India,Right hand Bat,Right arm Medium fast,Allrounder,Hardik Pandya swears by living life king size ...
133,Dinesh Karthik,India,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Not many would forget the sight of Dinesh Kart...
134,Ravichandran Ashwin,India,Right hand Bat,Right arm Offbreak,Bowling Allrounder,R Ashwin took the tricks and skills he learned...
135,Bhuvneshwar Kumar,India,Right hand Bat,Right arm Medium,Bowler,"At the time of his India debut in 2012, Bhuvne..."
136,Arshdeep Singh,India,Left hand Bat,Left arm Medium fast,Bowler,
137,Mohammed Shami,India,Right hand Bat,Right arm Fast,Bowler,Mohammed Shami was India's leading fast bowler...
192,Deepak Hooda,India,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."
211,Rishabh Pant,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."

In [38]:
df_player.to_csv('D:/harshita/project/file2/csv/player.csv',index=False)